version: '3.8'

services:
  backend:
    build: ./backend
    container_name: chatbot-backend-container
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL:-deepseek-r1:7b}
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: chatbot-frontend-container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
